/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceV1SourceIpMappingFetchSourceIpMapping } from "../../funcs/voiceV1SourceIpMappingFetchSourceIpMapping.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.FetchSourceIpMappingRequest$inboundSchema,
};

export const tool$voiceV1SourceIpMappingFetchSourceIpMapping: ToolDefinition<
  typeof args
> = {
  name: "voice-v1-source-ip-mapping_fetch-source-ip-mapping",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await voiceV1SourceIpMappingFetchSourceIpMapping(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
