/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceV1ByocTrunkUpdateByocTrunk } from "../../funcs/voiceV1ByocTrunkUpdateByocTrunk.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateByocTrunkRequest$inboundSchema,
};

export const tool$voiceV1ByocTrunkUpdateByocTrunk: ToolDefinition<typeof args> =
  {
    name: "voice-v1-byoc-trunk_update-byoc-trunk",
    description: ``,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await voiceV1ByocTrunkUpdateByocTrunk(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value.result;

      return formatResult(value, apiCall);
    },
  };
