/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceV1IpRecordDeleteIpRecord } from "../../funcs/voiceV1IpRecordDeleteIpRecord.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteIpRecordRequest$inboundSchema,
};

export const tool$voiceV1IpRecordDeleteIpRecord: ToolDefinition<typeof args> = {
  name: "voice-v1-ip-record_delete-ip-record",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await voiceV1IpRecordDeleteIpRecord(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
