/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceV1ConnectionPolicyFetchConnectionPolicy } from "../../funcs/voiceV1ConnectionPolicyFetchConnectionPolicy.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.FetchConnectionPolicyRequest$inboundSchema,
};

export const tool$voiceV1ConnectionPolicyFetchConnectionPolicy: ToolDefinition<
  typeof args
> = {
  name: "voice-v1-connection-policy_fetch-connection-policy",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] =
      await voiceV1ConnectionPolicyFetchConnectionPolicy(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
