/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceV1SettingsFetchDialingPermissionsSettings } from "../../funcs/voiceV1SettingsFetchDialingPermissionsSettings.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$voiceV1SettingsFetchDialingPermissionsSettings:
  ToolDefinition = {
    name: "voice-v1-settings_fetch-dialing-permissions-settings",
    description:
      `Retrieve voice dialing permissions inheritance for the sub-account`,
    tool: async (client, ctx) => {
      const [result, apiCall] =
        await voiceV1SettingsFetchDialingPermissionsSettings(
          client,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value.result;

      return formatResult(value, apiCall);
    },
  };
