/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceV1ConnectionPolicyTargetDeleteConnectionPolicyTarget } from "../../funcs/voiceV1ConnectionPolicyTargetDeleteConnectionPolicyTarget.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteConnectionPolicyTargetRequest$inboundSchema,
};

export const tool$voiceV1ConnectionPolicyTargetDeleteConnectionPolicyTarget:
  ToolDefinition<typeof args> = {
    name: "voice-v1-connection-policy-target_delete-connection-policy-target",
    description: ``,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await voiceV1ConnectionPolicyTargetDeleteConnectionPolicyTarget(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
