/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceV1IpRecordFetchIpRecord } from "../../funcs/voiceV1IpRecordFetchIpRecord.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.FetchIpRecordRequest$inboundSchema,
};

export const tool$voiceV1IpRecordFetchIpRecord: ToolDefinition<typeof args> = {
  name: "voice-v1-ip-record_fetch-ip-record",
  description: ``,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await voiceV1IpRecordFetchIpRecord(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
