/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceV1CountryFetchDialingPermissionsCountry } from "../../funcs/voiceV1CountryFetchDialingPermissionsCountry.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.FetchDialingPermissionsCountryRequest$inboundSchema,
};

export const tool$voiceV1CountryFetchDialingPermissionsCountry: ToolDefinition<
  typeof args
> = {
  name: "voice-v1-country_fetch-dialing-permissions-country",
  description:
    `Retrieve voice dialing country permissions identified by the given ISO country code`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] =
      await voiceV1CountryFetchDialingPermissionsCountry(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
