/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceV1SettingsUpdateDialingPermissionsSettings } from "../../funcs/voiceV1SettingsUpdateDialingPermissionsSettings.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations
    .UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest$inboundSchema
    .optional(),
};

export const tool$voiceV1SettingsUpdateDialingPermissionsSettings:
  ToolDefinition<typeof args> = {
    name: "voice-v1-settings_update-dialing-permissions-settings",
    description:
      `Update voice dialing permissions inheritance for the sub-account`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await voiceV1SettingsUpdateDialingPermissionsSettings(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value.result;

      return formatResult(value, apiCall);
    },
  };
