/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { VoiceV1ArchivedCall } from "./voicev1archivedcall.js";
import { VoiceV1BulkCountryUpdate } from "./voicev1bulkcountryupdate.js";
import { VoiceV1ByocTrunk } from "./voicev1byoctrunk.js";
import { VoiceV1ConnectionPolicy } from "./voicev1connectionpolicy.js";
import { VoiceV1ConnectionPolicyTarget } from "./voicev1connectionpolicytarget.js";
import { VoiceV1Country } from "./voicev1country.js";
import { VoiceV1HighriskSpecialPrefix } from "./voicev1highriskspecialprefix.js";
import { VoiceV1IpRecord } from "./voicev1iprecord.js";
import { VoiceV1Settings } from "./voicev1settings.js";
import { VoiceV1SourceIpMapping } from "./voicev1sourceipmapping.js";

export class TwilioVoice extends ClientSDK {
  private _voiceV1ArchivedCall?: VoiceV1ArchivedCall;
  get voiceV1ArchivedCall(): VoiceV1ArchivedCall {
    return (this._voiceV1ArchivedCall ??= new VoiceV1ArchivedCall(
      this._options,
    ));
  }

  private _voiceV1ByocTrunk?: VoiceV1ByocTrunk;
  get voiceV1ByocTrunk(): VoiceV1ByocTrunk {
    return (this._voiceV1ByocTrunk ??= new VoiceV1ByocTrunk(this._options));
  }

  private _voiceV1ConnectionPolicy?: VoiceV1ConnectionPolicy;
  get voiceV1ConnectionPolicy(): VoiceV1ConnectionPolicy {
    return (this._voiceV1ConnectionPolicy ??= new VoiceV1ConnectionPolicy(
      this._options,
    ));
  }

  private _voiceV1ConnectionPolicyTarget?: VoiceV1ConnectionPolicyTarget;
  get voiceV1ConnectionPolicyTarget(): VoiceV1ConnectionPolicyTarget {
    return (this._voiceV1ConnectionPolicyTarget ??=
      new VoiceV1ConnectionPolicyTarget(this._options));
  }

  private _voiceV1Country?: VoiceV1Country;
  get voiceV1Country(): VoiceV1Country {
    return (this._voiceV1Country ??= new VoiceV1Country(this._options));
  }

  private _voiceV1BulkCountryUpdate?: VoiceV1BulkCountryUpdate;
  get voiceV1BulkCountryUpdate(): VoiceV1BulkCountryUpdate {
    return (this._voiceV1BulkCountryUpdate ??= new VoiceV1BulkCountryUpdate(
      this._options,
    ));
  }

  private _voiceV1HighriskSpecialPrefix?: VoiceV1HighriskSpecialPrefix;
  get voiceV1HighriskSpecialPrefix(): VoiceV1HighriskSpecialPrefix {
    return (this._voiceV1HighriskSpecialPrefix ??=
      new VoiceV1HighriskSpecialPrefix(this._options));
  }

  private _voiceV1Settings?: VoiceV1Settings;
  get voiceV1Settings(): VoiceV1Settings {
    return (this._voiceV1Settings ??= new VoiceV1Settings(this._options));
  }

  private _voiceV1IpRecord?: VoiceV1IpRecord;
  get voiceV1IpRecord(): VoiceV1IpRecord {
    return (this._voiceV1IpRecord ??= new VoiceV1IpRecord(this._options));
  }

  private _voiceV1SourceIpMapping?: VoiceV1SourceIpMapping;
  get voiceV1SourceIpMapping(): VoiceV1SourceIpMapping {
    return (this._voiceV1SourceIpMapping ??= new VoiceV1SourceIpMapping(
      this._options,
    ));
  }
}
