/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceV1SettingsFetchDialingPermissionsSettings } from "../funcs/voiceV1SettingsFetchDialingPermissionsSettings.js";
import { voiceV1SettingsUpdateDialingPermissionsSettings } from "../funcs/voiceV1SettingsUpdateDialingPermissionsSettings.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class VoiceV1Settings extends ClientSDK {
  /**
   * Retrieve voice dialing permissions inheritance for the sub-account
   */
  async fetchDialingPermissionsSettings(
    options?: RequestOptions,
  ): Promise<operations.FetchDialingPermissionsSettingsResponse> {
    return unwrapAsync(voiceV1SettingsFetchDialingPermissionsSettings(
      this,
      options,
    ));
  }

  /**
   * Update voice dialing permissions inheritance for the sub-account
   */
  async updateDialingPermissionsSettings(
    request?:
      | operations.UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.UpdateDialingPermissionsSettingsResponse> {
    return unwrapAsync(voiceV1SettingsUpdateDialingPermissionsSettings(
      this,
      request,
      options,
    ));
  }
}
