/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceV1BulkCountryUpdateCreateDialingPermissionsCountryBulkUpdate } from "../funcs/voiceV1BulkCountryUpdateCreateDialingPermissionsCountryBulkUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class VoiceV1BulkCountryUpdate extends ClientSDK {
  /**
   * Create a bulk update request to change voice dialing country permissions of one or more countries identified by the corresponding [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
   */
  async createDialingPermissionsCountryBulkUpdate(
    request?:
      | operations.CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.CreateDialingPermissionsCountryBulkUpdateResponse> {
    return unwrapAsync(
      voiceV1BulkCountryUpdateCreateDialingPermissionsCountryBulkUpdate(
        this,
        request,
        options,
      ),
    );
  }
}
