/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceV1CountryFetchDialingPermissionsCountry } from "../funcs/voiceV1CountryFetchDialingPermissionsCountry.js";
import { voiceV1CountryListDialingPermissionsCountry } from "../funcs/voiceV1CountryListDialingPermissionsCountry.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class VoiceV1Country extends ClientSDK {
  /**
   * Retrieve voice dialing country permissions identified by the given ISO country code
   */
  async fetchDialingPermissionsCountry(
    request: operations.FetchDialingPermissionsCountryRequest,
    options?: RequestOptions,
  ): Promise<operations.FetchDialingPermissionsCountryResponse> {
    return unwrapAsync(voiceV1CountryFetchDialingPermissionsCountry(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve all voice dialing country permissions for this account
   */
  async listDialingPermissionsCountry(
    request: operations.ListDialingPermissionsCountryRequest,
    options?: RequestOptions,
  ): Promise<operations.ListDialingPermissionsCountryResponse> {
    return unwrapAsync(voiceV1CountryListDialingPermissionsCountry(
      this,
      request,
      options,
    ));
  }
}
