/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voiceV1IpRecordCreateIpRecord } from "../funcs/voiceV1IpRecordCreateIpRecord.js";
import { voiceV1IpRecordDeleteIpRecord } from "../funcs/voiceV1IpRecordDeleteIpRecord.js";
import { voiceV1IpRecordFetchIpRecord } from "../funcs/voiceV1IpRecordFetchIpRecord.js";
import { voiceV1IpRecordListIpRecord } from "../funcs/voiceV1IpRecordListIpRecord.js";
import { voiceV1IpRecordUpdateIpRecord } from "../funcs/voiceV1IpRecordUpdateIpRecord.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class VoiceV1IpRecord extends ClientSDK {
  async createIpRecord(
    request?: operations.CreateIpRecordCreateIpRecordRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.CreateIpRecordResponse> {
    return unwrapAsync(voiceV1IpRecordCreateIpRecord(
      this,
      request,
      options,
    ));
  }

  async listIpRecord(
    request: operations.ListIpRecordRequest,
    options?: RequestOptions,
  ): Promise<operations.ListIpRecordResponse> {
    return unwrapAsync(voiceV1IpRecordListIpRecord(
      this,
      request,
      options,
    ));
  }

  async fetchIpRecord(
    request: operations.FetchIpRecordRequest,
    options?: RequestOptions,
  ): Promise<operations.FetchIpRecordResponse> {
    return unwrapAsync(voiceV1IpRecordFetchIpRecord(
      this,
      request,
      options,
    ));
  }

  async updateIpRecord(
    request: operations.UpdateIpRecordRequest,
    options?: RequestOptions,
  ): Promise<operations.UpdateIpRecordResponse> {
    return unwrapAsync(voiceV1IpRecordUpdateIpRecord(
      this,
      request,
      options,
    ));
  }

  async deleteIpRecord(
    request: operations.DeleteIpRecordRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(voiceV1IpRecordDeleteIpRecord(
      this,
      request,
      options,
    ));
  }
}
