/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const CreateDialingPermissionsCountryBulkUpdateServerList = [
  "https://voice.twilio.com",
] as const;

export type CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest =
  {
    /**
     * URL encoded JSON array of update objects. example : `[ { "iso_code": "GB", "low_risk_numbers_enabled": "true", "high_risk_special_numbers_enabled":"true", "high_risk_tollfraud_numbers_enabled": "false" } ]`
     */
    updateRequest: string;
  };

export type CreateDialingPermissionsCountryBulkUpdateResponse = {
  headers: { [k: string]: Array<string> };
  result:
    components.VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate;
};

/** @internal */
export const CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest$inboundSchema:
  z.ZodType<
    CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    UpdateRequest: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "UpdateRequest": "updateRequest",
    });
  });

/** @internal */
export type CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest$Outbound =
  {
    UpdateRequest: string;
  };

/** @internal */
export const CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest$outboundSchema:
  z.ZodType<
    CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest$Outbound,
    z.ZodTypeDef,
    CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest
  > = z.object({
    updateRequest: z.string(),
  }).transform((v) => {
    return remap$(v, {
      updateRequest: "UpdateRequest",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest$ {
  /** @deprecated use `CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest$inboundSchema` instead. */
  export const inboundSchema =
    CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest$inboundSchema;
  /** @deprecated use `CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest$outboundSchema` instead. */
  export const outboundSchema =
    CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest$outboundSchema;
  /** @deprecated use `CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest$Outbound` instead. */
  export type Outbound =
    CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest$Outbound;
}

export function createDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequestToJSON(
  createDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest:
    CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest,
): string {
  return JSON.stringify(
    CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest$outboundSchema
      .parse(
        createDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest,
      ),
  );
}

export function createDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'CreateDialingPermissionsCountryBulkUpdateCreateDialingPermissionsCountryBulkUpdateRequest' from JSON`,
  );
}

/** @internal */
export const CreateDialingPermissionsCountryBulkUpdateResponse$inboundSchema:
  z.ZodType<
    CreateDialingPermissionsCountryBulkUpdateResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    Headers: z.record(z.array(z.string())),
    Result:
      components
        .VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate$inboundSchema,
  }).transform((v) => {
    return remap$(v, {
      "Headers": "headers",
      "Result": "result",
    });
  });

/** @internal */
export type CreateDialingPermissionsCountryBulkUpdateResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result:
    components.VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate$Outbound;
};

/** @internal */
export const CreateDialingPermissionsCountryBulkUpdateResponse$outboundSchema:
  z.ZodType<
    CreateDialingPermissionsCountryBulkUpdateResponse$Outbound,
    z.ZodTypeDef,
    CreateDialingPermissionsCountryBulkUpdateResponse
  > = z.object({
    headers: z.record(z.array(z.string())),
    result:
      components
        .VoiceV1DialingPermissionsDialingPermissionsCountryBulkUpdate$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      headers: "Headers",
      result: "Result",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateDialingPermissionsCountryBulkUpdateResponse$ {
  /** @deprecated use `CreateDialingPermissionsCountryBulkUpdateResponse$inboundSchema` instead. */
  export const inboundSchema =
    CreateDialingPermissionsCountryBulkUpdateResponse$inboundSchema;
  /** @deprecated use `CreateDialingPermissionsCountryBulkUpdateResponse$outboundSchema` instead. */
  export const outboundSchema =
    CreateDialingPermissionsCountryBulkUpdateResponse$outboundSchema;
  /** @deprecated use `CreateDialingPermissionsCountryBulkUpdateResponse$Outbound` instead. */
  export type Outbound =
    CreateDialingPermissionsCountryBulkUpdateResponse$Outbound;
}

export function createDialingPermissionsCountryBulkUpdateResponseToJSON(
  createDialingPermissionsCountryBulkUpdateResponse:
    CreateDialingPermissionsCountryBulkUpdateResponse,
): string {
  return JSON.stringify(
    CreateDialingPermissionsCountryBulkUpdateResponse$outboundSchema.parse(
      createDialingPermissionsCountryBulkUpdateResponse,
    ),
  );
}

export function createDialingPermissionsCountryBulkUpdateResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  CreateDialingPermissionsCountryBulkUpdateResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      CreateDialingPermissionsCountryBulkUpdateResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'CreateDialingPermissionsCountryBulkUpdateResponse' from JSON`,
  );
}
