/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const DeleteConnectionPolicyServerList = [
  "https://voice.twilio.com",
] as const;

export type DeleteConnectionPolicyRequest = {
  /**
   * The unique string that we created to identify the Connection Policy resource to delete.
   */
  sid: string;
};

/** @internal */
export const DeleteConnectionPolicyRequest$inboundSchema: z.ZodType<
  DeleteConnectionPolicyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  Sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "Sid": "sid",
  });
});

/** @internal */
export type DeleteConnectionPolicyRequest$Outbound = {
  Sid: string;
};

/** @internal */
export const DeleteConnectionPolicyRequest$outboundSchema: z.ZodType<
  DeleteConnectionPolicyRequest$Outbound,
  z.ZodTypeDef,
  DeleteConnectionPolicyRequest
> = z.object({
  sid: z.string(),
}).transform((v) => {
  return remap$(v, {
    sid: "Sid",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteConnectionPolicyRequest$ {
  /** @deprecated use `DeleteConnectionPolicyRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteConnectionPolicyRequest$inboundSchema;
  /** @deprecated use `DeleteConnectionPolicyRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteConnectionPolicyRequest$outboundSchema;
  /** @deprecated use `DeleteConnectionPolicyRequest$Outbound` instead. */
  export type Outbound = DeleteConnectionPolicyRequest$Outbound;
}

export function deleteConnectionPolicyRequestToJSON(
  deleteConnectionPolicyRequest: DeleteConnectionPolicyRequest,
): string {
  return JSON.stringify(
    DeleteConnectionPolicyRequest$outboundSchema.parse(
      deleteConnectionPolicyRequest,
    ),
  );
}

export function deleteConnectionPolicyRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteConnectionPolicyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteConnectionPolicyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteConnectionPolicyRequest' from JSON`,
  );
}
