/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const FetchDialingPermissionsSettingsServerList = [
  "https://voice.twilio.com",
] as const;

export type FetchDialingPermissionsSettingsResponse = {
  headers: { [k: string]: Array<string> };
  result: components.VoiceV1DialingPermissionsDialingPermissionsSettings;
};

/** @internal */
export const FetchDialingPermissionsSettingsResponse$inboundSchema: z.ZodType<
  FetchDialingPermissionsSettingsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result:
    components
      .VoiceV1DialingPermissionsDialingPermissionsSettings$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type FetchDialingPermissionsSettingsResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result:
    components.VoiceV1DialingPermissionsDialingPermissionsSettings$Outbound;
};

/** @internal */
export const FetchDialingPermissionsSettingsResponse$outboundSchema: z.ZodType<
  FetchDialingPermissionsSettingsResponse$Outbound,
  z.ZodTypeDef,
  FetchDialingPermissionsSettingsResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result:
    components
      .VoiceV1DialingPermissionsDialingPermissionsSettings$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FetchDialingPermissionsSettingsResponse$ {
  /** @deprecated use `FetchDialingPermissionsSettingsResponse$inboundSchema` instead. */
  export const inboundSchema =
    FetchDialingPermissionsSettingsResponse$inboundSchema;
  /** @deprecated use `FetchDialingPermissionsSettingsResponse$outboundSchema` instead. */
  export const outboundSchema =
    FetchDialingPermissionsSettingsResponse$outboundSchema;
  /** @deprecated use `FetchDialingPermissionsSettingsResponse$Outbound` instead. */
  export type Outbound = FetchDialingPermissionsSettingsResponse$Outbound;
}

export function fetchDialingPermissionsSettingsResponseToJSON(
  fetchDialingPermissionsSettingsResponse:
    FetchDialingPermissionsSettingsResponse,
): string {
  return JSON.stringify(
    FetchDialingPermissionsSettingsResponse$outboundSchema.parse(
      fetchDialingPermissionsSettingsResponse,
    ),
  );
}

export function fetchDialingPermissionsSettingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  FetchDialingPermissionsSettingsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      FetchDialingPermissionsSettingsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'FetchDialingPermissionsSettingsResponse' from JSON`,
  );
}
