/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const UpdateDialingPermissionsSettingsServerList = [
  "https://voice.twilio.com",
] as const;

export type UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest =
  {
    /**
     * `true` for the sub-account to inherit voice dialing permissions from the Master Project; otherwise `false`.
     */
    dialingPermissionsInheritance?: boolean | undefined;
  };

export type UpdateDialingPermissionsSettingsResponse = {
  headers: { [k: string]: Array<string> };
  result: components.VoiceV1DialingPermissionsDialingPermissionsSettings;
};

/** @internal */
export const UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest$inboundSchema:
  z.ZodType<
    UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    DialingPermissionsInheritance: z.boolean().optional(),
  }).transform((v) => {
    return remap$(v, {
      "DialingPermissionsInheritance": "dialingPermissionsInheritance",
    });
  });

/** @internal */
export type UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest$Outbound =
  {
    DialingPermissionsInheritance?: boolean | undefined;
  };

/** @internal */
export const UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest$outboundSchema:
  z.ZodType<
    UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest$Outbound,
    z.ZodTypeDef,
    UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest
  > = z.object({
    dialingPermissionsInheritance: z.boolean().optional(),
  }).transform((v) => {
    return remap$(v, {
      dialingPermissionsInheritance: "DialingPermissionsInheritance",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest$ {
  /** @deprecated use `UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest$inboundSchema` instead. */
  export const inboundSchema =
    UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest$inboundSchema;
  /** @deprecated use `UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest$outboundSchema` instead. */
  export const outboundSchema =
    UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest$outboundSchema;
  /** @deprecated use `UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest$Outbound` instead. */
  export type Outbound =
    UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest$Outbound;
}

export function updateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequestToJSON(
  updateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest:
    UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest,
): string {
  return JSON.stringify(
    UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest$outboundSchema
      .parse(
        updateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest,
      ),
  );
}

export function updateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'UpdateDialingPermissionsSettingsUpdateDialingPermissionsSettingsRequest' from JSON`,
  );
}

/** @internal */
export const UpdateDialingPermissionsSettingsResponse$inboundSchema: z.ZodType<
  UpdateDialingPermissionsSettingsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result:
    components
      .VoiceV1DialingPermissionsDialingPermissionsSettings$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type UpdateDialingPermissionsSettingsResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result:
    components.VoiceV1DialingPermissionsDialingPermissionsSettings$Outbound;
};

/** @internal */
export const UpdateDialingPermissionsSettingsResponse$outboundSchema: z.ZodType<
  UpdateDialingPermissionsSettingsResponse$Outbound,
  z.ZodTypeDef,
  UpdateDialingPermissionsSettingsResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result:
    components
      .VoiceV1DialingPermissionsDialingPermissionsSettings$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateDialingPermissionsSettingsResponse$ {
  /** @deprecated use `UpdateDialingPermissionsSettingsResponse$inboundSchema` instead. */
  export const inboundSchema =
    UpdateDialingPermissionsSettingsResponse$inboundSchema;
  /** @deprecated use `UpdateDialingPermissionsSettingsResponse$outboundSchema` instead. */
  export const outboundSchema =
    UpdateDialingPermissionsSettingsResponse$outboundSchema;
  /** @deprecated use `UpdateDialingPermissionsSettingsResponse$Outbound` instead. */
  export type Outbound = UpdateDialingPermissionsSettingsResponse$Outbound;
}

export function updateDialingPermissionsSettingsResponseToJSON(
  updateDialingPermissionsSettingsResponse:
    UpdateDialingPermissionsSettingsResponse,
): string {
  return JSON.stringify(
    UpdateDialingPermissionsSettingsResponse$outboundSchema.parse(
      updateDialingPermissionsSettingsResponse,
    ),
  );
}

export function updateDialingPermissionsSettingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateDialingPermissionsSettingsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateDialingPermissionsSettingsResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateDialingPermissionsSettingsResponse' from JSON`,
  );
}
