/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type VoiceV1DialingPermissionsDialingPermissionsSettings = {
  /**
   * `true` if the sub-account will inherit voice dialing permissions from the Master Project; otherwise `false`.
   */
  dialingPermissionsInheritance?: boolean | null | undefined;
  /**
   * The absolute URL of this resource.
   */
  url?: string | null | undefined;
};

/** @internal */
export const VoiceV1DialingPermissionsDialingPermissionsSettings$inboundSchema:
  z.ZodType<
    VoiceV1DialingPermissionsDialingPermissionsSettings,
    z.ZodTypeDef,
    unknown
  > = z.object({
    dialing_permissions_inheritance: z.nullable(z.boolean()).optional(),
    url: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "dialing_permissions_inheritance": "dialingPermissionsInheritance",
    });
  });

/** @internal */
export type VoiceV1DialingPermissionsDialingPermissionsSettings$Outbound = {
  dialing_permissions_inheritance?: boolean | null | undefined;
  url?: string | null | undefined;
};

/** @internal */
export const VoiceV1DialingPermissionsDialingPermissionsSettings$outboundSchema:
  z.ZodType<
    VoiceV1DialingPermissionsDialingPermissionsSettings$Outbound,
    z.ZodTypeDef,
    VoiceV1DialingPermissionsDialingPermissionsSettings
  > = z.object({
    dialingPermissionsInheritance: z.nullable(z.boolean()).optional(),
    url: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      dialingPermissionsInheritance: "dialing_permissions_inheritance",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VoiceV1DialingPermissionsDialingPermissionsSettings$ {
  /** @deprecated use `VoiceV1DialingPermissionsDialingPermissionsSettings$inboundSchema` instead. */
  export const inboundSchema =
    VoiceV1DialingPermissionsDialingPermissionsSettings$inboundSchema;
  /** @deprecated use `VoiceV1DialingPermissionsDialingPermissionsSettings$outboundSchema` instead. */
  export const outboundSchema =
    VoiceV1DialingPermissionsDialingPermissionsSettings$outboundSchema;
  /** @deprecated use `VoiceV1DialingPermissionsDialingPermissionsSettings$Outbound` instead. */
  export type Outbound =
    VoiceV1DialingPermissionsDialingPermissionsSettings$Outbound;
}

export function voiceV1DialingPermissionsDialingPermissionsSettingsToJSON(
  voiceV1DialingPermissionsDialingPermissionsSettings:
    VoiceV1DialingPermissionsDialingPermissionsSettings,
): string {
  return JSON.stringify(
    VoiceV1DialingPermissionsDialingPermissionsSettings$outboundSchema.parse(
      voiceV1DialingPermissionsDialingPermissionsSettings,
    ),
  );
}

export function voiceV1DialingPermissionsDialingPermissionsSettingsFromJSON(
  jsonString: string,
): SafeParseResult<
  VoiceV1DialingPermissionsDialingPermissionsSettings,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      VoiceV1DialingPermissionsDialingPermissionsSettings$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'VoiceV1DialingPermissionsDialingPermissionsSettings' from JSON`,
  );
}
