/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A list of URLs related to this resource.
 */
export type VoiceV1DialingPermissionsDialingPermissionsCountryLinks = {};

export type VoiceV1DialingPermissionsDialingPermissionsCountry = {
  /**
   * The [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
   */
  isoCode?: string | null | undefined;
  /**
   * The name of the country.
   */
  name?: string | null | undefined;
  /**
   * The name of the continent in which the country is located.
   */
  continent?: string | null | undefined;
  /**
   * The E.164 assigned [country codes(s)](https://www.itu.int/itudoc/itu-t/ob-lists/icc/e164_763.html)
   */
  countryCodes?: Array<string> | null | undefined;
  /**
   * Whether dialing to low-risk numbers is enabled.
   */
  lowRiskNumbersEnabled?: boolean | null | undefined;
  /**
   * Whether dialing to high-risk special services numbers is enabled. These prefixes include number ranges allocated by the country and include premium numbers, special services, shared cost, and others
   */
  highRiskSpecialNumbersEnabled?: boolean | null | undefined;
  /**
   * Whether dialing to high-risk [toll fraud](https://www.twilio.com/blog/how-to-protect-your-account-from-toll-fraud-with-voice-dialing-geo-permissions-html) numbers is enabled. These prefixes include narrow number ranges that have a high-risk of international revenue sharing fraud (IRSF) attacks, also known as [toll fraud](https://www.twilio.com/blog/how-to-protect-your-account-from-toll-fraud-with-voice-dialing-geo-permissions-html). These prefixes are collected from anti-fraud databases and verified by analyzing calls on our network. These prefixes are not available for download and are updated frequently
   */
  highRiskTollfraudNumbersEnabled?: boolean | null | undefined;
  /**
   * The absolute URL of this resource.
   */
  url?: string | null | undefined;
  /**
   * A list of URLs related to this resource.
   */
  links?:
    | VoiceV1DialingPermissionsDialingPermissionsCountryLinks
    | null
    | undefined;
};

/** @internal */
export const VoiceV1DialingPermissionsDialingPermissionsCountryLinks$inboundSchema:
  z.ZodType<
    VoiceV1DialingPermissionsDialingPermissionsCountryLinks,
    z.ZodTypeDef,
    unknown
  > = z.object({});

/** @internal */
export type VoiceV1DialingPermissionsDialingPermissionsCountryLinks$Outbound =
  {};

/** @internal */
export const VoiceV1DialingPermissionsDialingPermissionsCountryLinks$outboundSchema:
  z.ZodType<
    VoiceV1DialingPermissionsDialingPermissionsCountryLinks$Outbound,
    z.ZodTypeDef,
    VoiceV1DialingPermissionsDialingPermissionsCountryLinks
  > = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VoiceV1DialingPermissionsDialingPermissionsCountryLinks$ {
  /** @deprecated use `VoiceV1DialingPermissionsDialingPermissionsCountryLinks$inboundSchema` instead. */
  export const inboundSchema =
    VoiceV1DialingPermissionsDialingPermissionsCountryLinks$inboundSchema;
  /** @deprecated use `VoiceV1DialingPermissionsDialingPermissionsCountryLinks$outboundSchema` instead. */
  export const outboundSchema =
    VoiceV1DialingPermissionsDialingPermissionsCountryLinks$outboundSchema;
  /** @deprecated use `VoiceV1DialingPermissionsDialingPermissionsCountryLinks$Outbound` instead. */
  export type Outbound =
    VoiceV1DialingPermissionsDialingPermissionsCountryLinks$Outbound;
}

export function voiceV1DialingPermissionsDialingPermissionsCountryLinksToJSON(
  voiceV1DialingPermissionsDialingPermissionsCountryLinks:
    VoiceV1DialingPermissionsDialingPermissionsCountryLinks,
): string {
  return JSON.stringify(
    VoiceV1DialingPermissionsDialingPermissionsCountryLinks$outboundSchema
      .parse(voiceV1DialingPermissionsDialingPermissionsCountryLinks),
  );
}

export function voiceV1DialingPermissionsDialingPermissionsCountryLinksFromJSON(
  jsonString: string,
): SafeParseResult<
  VoiceV1DialingPermissionsDialingPermissionsCountryLinks,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      VoiceV1DialingPermissionsDialingPermissionsCountryLinks$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'VoiceV1DialingPermissionsDialingPermissionsCountryLinks' from JSON`,
  );
}

/** @internal */
export const VoiceV1DialingPermissionsDialingPermissionsCountry$inboundSchema:
  z.ZodType<
    VoiceV1DialingPermissionsDialingPermissionsCountry,
    z.ZodTypeDef,
    unknown
  > = z.object({
    iso_code: z.nullable(z.string()).optional(),
    name: z.nullable(z.string()).optional(),
    continent: z.nullable(z.string()).optional(),
    country_codes: z.nullable(z.array(z.string())).optional(),
    low_risk_numbers_enabled: z.nullable(z.boolean()).optional(),
    high_risk_special_numbers_enabled: z.nullable(z.boolean()).optional(),
    high_risk_tollfraud_numbers_enabled: z.nullable(z.boolean()).optional(),
    url: z.nullable(z.string()).optional(),
    links: z.nullable(
      z.lazy(() =>
        VoiceV1DialingPermissionsDialingPermissionsCountryLinks$inboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "iso_code": "isoCode",
      "country_codes": "countryCodes",
      "low_risk_numbers_enabled": "lowRiskNumbersEnabled",
      "high_risk_special_numbers_enabled": "highRiskSpecialNumbersEnabled",
      "high_risk_tollfraud_numbers_enabled": "highRiskTollfraudNumbersEnabled",
    });
  });

/** @internal */
export type VoiceV1DialingPermissionsDialingPermissionsCountry$Outbound = {
  iso_code?: string | null | undefined;
  name?: string | null | undefined;
  continent?: string | null | undefined;
  country_codes?: Array<string> | null | undefined;
  low_risk_numbers_enabled?: boolean | null | undefined;
  high_risk_special_numbers_enabled?: boolean | null | undefined;
  high_risk_tollfraud_numbers_enabled?: boolean | null | undefined;
  url?: string | null | undefined;
  links?:
    | VoiceV1DialingPermissionsDialingPermissionsCountryLinks$Outbound
    | null
    | undefined;
};

/** @internal */
export const VoiceV1DialingPermissionsDialingPermissionsCountry$outboundSchema:
  z.ZodType<
    VoiceV1DialingPermissionsDialingPermissionsCountry$Outbound,
    z.ZodTypeDef,
    VoiceV1DialingPermissionsDialingPermissionsCountry
  > = z.object({
    isoCode: z.nullable(z.string()).optional(),
    name: z.nullable(z.string()).optional(),
    continent: z.nullable(z.string()).optional(),
    countryCodes: z.nullable(z.array(z.string())).optional(),
    lowRiskNumbersEnabled: z.nullable(z.boolean()).optional(),
    highRiskSpecialNumbersEnabled: z.nullable(z.boolean()).optional(),
    highRiskTollfraudNumbersEnabled: z.nullable(z.boolean()).optional(),
    url: z.nullable(z.string()).optional(),
    links: z.nullable(
      z.lazy(() =>
        VoiceV1DialingPermissionsDialingPermissionsCountryLinks$outboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      isoCode: "iso_code",
      countryCodes: "country_codes",
      lowRiskNumbersEnabled: "low_risk_numbers_enabled",
      highRiskSpecialNumbersEnabled: "high_risk_special_numbers_enabled",
      highRiskTollfraudNumbersEnabled: "high_risk_tollfraud_numbers_enabled",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VoiceV1DialingPermissionsDialingPermissionsCountry$ {
  /** @deprecated use `VoiceV1DialingPermissionsDialingPermissionsCountry$inboundSchema` instead. */
  export const inboundSchema =
    VoiceV1DialingPermissionsDialingPermissionsCountry$inboundSchema;
  /** @deprecated use `VoiceV1DialingPermissionsDialingPermissionsCountry$outboundSchema` instead. */
  export const outboundSchema =
    VoiceV1DialingPermissionsDialingPermissionsCountry$outboundSchema;
  /** @deprecated use `VoiceV1DialingPermissionsDialingPermissionsCountry$Outbound` instead. */
  export type Outbound =
    VoiceV1DialingPermissionsDialingPermissionsCountry$Outbound;
}

export function voiceV1DialingPermissionsDialingPermissionsCountryToJSON(
  voiceV1DialingPermissionsDialingPermissionsCountry:
    VoiceV1DialingPermissionsDialingPermissionsCountry,
): string {
  return JSON.stringify(
    VoiceV1DialingPermissionsDialingPermissionsCountry$outboundSchema.parse(
      voiceV1DialingPermissionsDialingPermissionsCountry,
    ),
  );
}

export function voiceV1DialingPermissionsDialingPermissionsCountryFromJSON(
  jsonString: string,
): SafeParseResult<
  VoiceV1DialingPermissionsDialingPermissionsCountry,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      VoiceV1DialingPermissionsDialingPermissionsCountry$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'VoiceV1DialingPermissionsDialingPermissionsCountry' from JSON`,
  );
}
