/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type VoiceV1IpRecord = {
  /**
   * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the IP Record resource.
   */
  accountSid?: string | null | undefined;
  /**
   * The unique string that we created to identify the IP Record resource.
   */
  sid?: string | null | undefined;
  /**
   * The string that you assigned to describe the resource.
   */
  friendlyName?: string | null | undefined;
  /**
   * An IP address in dotted decimal notation, IPv4 only.
   */
  ipAddress?: string | null | undefined;
  /**
   * An integer representing the length of the [CIDR](https://tools.ietf.org/html/rfc4632) prefix to use with this IP address. By default the entire IP address is used, which for IPv4 is value 32.
   */
  cidrPrefixLength?: number | undefined;
  /**
   * The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
   */
  dateCreated?: Date | null | undefined;
  /**
   * The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
   */
  dateUpdated?: Date | null | undefined;
  /**
   * The absolute URL of the resource.
   */
  url?: string | null | undefined;
};

/** @internal */
export const VoiceV1IpRecord$inboundSchema: z.ZodType<
  VoiceV1IpRecord,
  z.ZodTypeDef,
  unknown
> = z.object({
  account_sid: z.nullable(z.string()).optional(),
  sid: z.nullable(z.string()).optional(),
  friendly_name: z.nullable(z.string()).optional(),
  ip_address: z.nullable(z.string()).optional(),
  cidr_prefix_length: z.number().int().default(0),
  date_created: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  date_updated: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  url: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "account_sid": "accountSid",
    "friendly_name": "friendlyName",
    "ip_address": "ipAddress",
    "cidr_prefix_length": "cidrPrefixLength",
    "date_created": "dateCreated",
    "date_updated": "dateUpdated",
  });
});

/** @internal */
export type VoiceV1IpRecord$Outbound = {
  account_sid?: string | null | undefined;
  sid?: string | null | undefined;
  friendly_name?: string | null | undefined;
  ip_address?: string | null | undefined;
  cidr_prefix_length: number;
  date_created?: string | null | undefined;
  date_updated?: string | null | undefined;
  url?: string | null | undefined;
};

/** @internal */
export const VoiceV1IpRecord$outboundSchema: z.ZodType<
  VoiceV1IpRecord$Outbound,
  z.ZodTypeDef,
  VoiceV1IpRecord
> = z.object({
  accountSid: z.nullable(z.string()).optional(),
  sid: z.nullable(z.string()).optional(),
  friendlyName: z.nullable(z.string()).optional(),
  ipAddress: z.nullable(z.string()).optional(),
  cidrPrefixLength: z.number().int().default(0),
  dateCreated: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  dateUpdated: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  url: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    accountSid: "account_sid",
    friendlyName: "friendly_name",
    ipAddress: "ip_address",
    cidrPrefixLength: "cidr_prefix_length",
    dateCreated: "date_created",
    dateUpdated: "date_updated",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VoiceV1IpRecord$ {
  /** @deprecated use `VoiceV1IpRecord$inboundSchema` instead. */
  export const inboundSchema = VoiceV1IpRecord$inboundSchema;
  /** @deprecated use `VoiceV1IpRecord$outboundSchema` instead. */
  export const outboundSchema = VoiceV1IpRecord$outboundSchema;
  /** @deprecated use `VoiceV1IpRecord$Outbound` instead. */
  export type Outbound = VoiceV1IpRecord$Outbound;
}

export function voiceV1IpRecordToJSON(
  voiceV1IpRecord: VoiceV1IpRecord,
): string {
  return JSON.stringify(VoiceV1IpRecord$outboundSchema.parse(voiceV1IpRecord));
}

export function voiceV1IpRecordFromJSON(
  jsonString: string,
): SafeParseResult<VoiceV1IpRecord, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VoiceV1IpRecord$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VoiceV1IpRecord' from JSON`,
  );
}
